### ISSUE TITLE
no work when changing ollama port

### ISSUE THREAD

**Issue by choigawoon** [valiantlynx/ollama-docker#6]
when changing ollama service port, webui cannot recognize it.

```
version: "3.8"

services:
  # app:
  #   build: .
  #   ports:
  #     - 8000:8000
  #     - 5678:5678
  #   volumes:
  #     - .:/code
  #   command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
  #   restart: always
  #   depends_on:
  #     - ollama
  #     - ollama-webui
  #   networks:
  #     - ollama-docker

  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3004:8080
    environment:
      - "/ollama/api=http://ollama:7869/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
```
